### ISSUE TITLE
gh-pages

### ISSUE THREAD

**Issue by multum-non-multa** [ddd-Makbema/pyEngine2D-ddd#22]
Go to the **settings** of your repository and ensure that the [publishing source branch](https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site) for your GitHub Page is set to `gh-pages`.

**Comment by ddd-Makbema** [comment]
now saved to gh-pages/docs

**Comment by ddd-Makbema** [comment]
Imma leave this open for now until we are able to fix the problems with formatting. when entering the gh-pages site it returns 404 until you go to /index.html

**Comment by ddd-Makbema** [comment]
its fixed now. make sure not to upload the built site, just the mkdocs.yml and the md files
